version: '3.3'

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=14001
      - PGID=14000
      - TZ=Etc/UTC
    volumes:
      - ${BASE}/nextcloud/config:/config
      - ${BASE}/data:/data
    ports:
      - 8082:80
    restart: unless-stopped

networks:
  default:
  nextcloud-network:
    external: true
    name: nextcloud-network

