version: '3.3'

services:
  nextclouddb:
    image: postgres:16
    container_name: nextclouddb
    user: 14002:14000
    restart: unless-stopped
    networks:
      - nextcloud-network
    env_file:
      - .env  
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    volumes:
      - ${BASE}/nextcloud/postgresql:/var/lib/postgresql/data
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
      
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    user: 14001:14000
    restart: always
    ports:
      - 8090:80
    volumes:
      - ${DOCKER_BASE}/nextcloud/html:/var/www/html
    networks:
      - nextcloud-network
    depends_on:
      - nextclouddb
    environment:
      - POSTGRES_HOST=nextclouddb
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user

networks:
  default:
  nextcloud-network:
    external: true
    name: nextcloud-network

secrets:
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password.txt # put admin password in this file
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user.txt # put admin username in this file
  postgres_db:
    file: ./secrets/postgres_db.txt # put postgresql db name in this file
  postgres_password:
    file: ./secrets/postgres_password.txt # put postgresql password in this file
  postgres_user:
    file: ./secrets/postgres_user.txt # put postgresql username in this file
