version: '3.3'

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    user: root
    ports: 
      - '8096:8096'
    volumes:
      - ${DOCKER_BASE}/jellyfin/config:/config
      - ${TV}:/data/tvshows
      - ${MOVIE}:/data/movies
    restart: 'unless-stopped'
  jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=${TZ}
       ports:
            - 5055:5055
       volumes:
            - ${DOCKER_BASE}/jellyseer/config:/app/config
       restart: unless-stopped
  prowlarr:
      image: lscr.io/linuxserver/prowlarr:latest
      container_name: prowlarr
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
      volumes:
        - ${DOCKER_BASE}/prowlarr/data:/config
      ports:
        - 9696:9696
      restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_BASE}/sonarr/config:/config
      - ${TV}:/tv #optional
      - ${DOWNLOADS}:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_BASE}/radarr/config:/config
      - ${MOVIE}:/movies #optional
      - ${DOWNLOADS}:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_BASE}/readarr/config:/config
      - ${BOOKS}:/books #optional
      - ${DOWNLOADS}:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_BASE}/lidarr/config:/config
      - ${MUSIC}:/music #optional
      - ${DOWNLOADS}:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_BASE}/bazarr/config:/config
      - ${MOVIE}:/movies #optional
      - ${TV}:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - ${DOCKER_BASE}/lazylibrarian/config:/config
      - ${DOWNLOADS}:/downloads
      - ${BOOKS}:/books #optional
    ports:
      - 5299:5299
    restart: unless-stopped
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_BASE}/freshrss/config:/config
    ports:
      - 82:82
    restart: unless-stopped
    
networks:
  default:
    external: true
    name: nginx-network
