# this compose holds apps for visualizing the status of docker containers and 
# keep information on other containers

version: "3.3"

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8888:8080
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    #command: --interval 10 --http-api-metrics --http-api-token demotoken --debug prometheus grafana parent child
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ${DOCKER_BASE}/prometheus:/etc/prometheus
      - ${DOCKER_BASE}/prometheus/prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ${DOCKER_BASE}/grafana:/etc/grafana/provisioning/datasources
