version: "3.7"

# tweaked from https://github.com/ynput/ayon-docker/tree/main

services:
  postgres:
    image: postgres:15
    container_name: ayon-postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ayon"]
      interval: 5s
      timeout: 5s
      retries: 5
    expose: [5432]
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./db:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=ayon"
      - "POSTGRES_PASSWORD=ayon"
      - "POSTGRES_DB=ayon"
    networks:
      - ayon-network

  redis:
    image: redis:alpine
    container_name: ayon-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ayon"]
      interval: 5s
      timeout: 5s
      retries: 5
    expose: [5432]
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./db:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=ayon"
      - "POSTGRES_PASSWORD=ayon"
      - "POSTGRES_DB=ayon"
    networks:
      - ayon-network

  redis:
    image: redis:alpine
    container_name: ayon-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5
    expose: [6379]
    networks:
      - ayon-network

  ayon:
    image: ynput/ayon:latest
    container_name: ayon-server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/info"]
      interval: 10s
      timeout: 2s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    # uncomment for older versions of Docker (>4.0.0) and comment out above "depends on" section.
    #depends_on:
      #- postgres
      #- redis
    expose: [5000]
    ports: ["5000:5000"]
    volumes:
      - "./addons:/addons"
      - "./storage:/storage"
      # comment out the following line on Windows
      - "/etc/localtime:/etc/localtime:ro"
      # uncomment the following line if you need to work on the backend code
      # - "./backend:/backend"
    networks:
      - nginx-network
      - ayon-network

volumes:
  db: {}

networks:
  nginx-network:
    external: True
  ayon-network:
    external: True
