# compose for a general use personal wiki and could serve as a template for specific wiki copies in the future

version: '3.3'

services:
  db:
    image: postgres:16
    container_name: wiki-personal-db
    user: 13002:13000
    restart: unless-stopped
    networks:
      - wiki-personal-network
    env_file:
      - .env  
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  wiki-personal:
    image: ghcr.io/requarks/wiki:2.5
    container_name: wiki-personal
    user: 13001:13000
    env_file:
      - .env
    networks:
      - wiki-personal-network
      - nginx-network
      - homepage-network
    volumes:
      - ./data/wiki:/wiki/data
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "${PORT}:3000"

networks:
  default:
  wiki-personal-network:
    name: wiki-personal-network
  nginx-network:
    external: true
    name: nginx-network
  homepage-network:
    external: true
    name: homepage-network
