# compose for a general use personal wiki and could serve as a template for specific wiki copies in the future

version: '3.3'

services:
  db:
    image: postgres:16
    user: 13002:13000
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - ./config/personal-wiki-config:/var/lib/postgresql/data

  wiki-personal:
    image: ghcr.io/requarks/wiki:3
    user: 13001:13000
    networks:
      - nginx-network
      - homepage-network
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "${PORT}:3000"

networks:
  default:
  nginx-network:
    external: true
    name: nginx-network
  homepage-network:
    external: true
    name: homepage-network
